name: "Read/Write data"
on: [push]

jobs:
  table:
    runs-on: ubuntu-latest
    name: Update index.html from json data
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - run: |
          npm i
          node generate.js
      - name: "Read/Write profiles' data"
        uses: EddieHubCommunity/gh-actions-html-table-generator@main
        with:
          json-file-path: ".cache/data.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          columns: 3
          file-to-use: "localisations.html"
          object-field-names: '[ "name", "lang", "desc", "1" ]'
          html-cell: '<h2>{{ lang }} by {{ name }}</h2><p>{{ desc }}</p><details><summary>See {{ lang }} by {{ name }} localisation proposals</summary><ul><li> {{ 1locale }}</li></ul></details>'